import { AnimateSharedLayout, motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import CodeMirror from '@uiw/react-codemirror';
import { json } from '@codemirror/lang-json';
import { html } from '@codemirror/lang-html';
import { xml } from '@codemirror/lang-xml';
import { dracula } from '@uiw/codemirror-theme-dracula';

const Home: NextPage = () => {

  const [tab, setTab] = useState(0);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-2 min-h-screen text-light-dark py-7 bg-dark">
        <div className="flex justify-center items-center">
          <button className="cool hover:underline hover:decoration-wavy decoration-1 underline-offset-2 decoration-purple-400 font-extrabold text-5xl text-center text-transparent bg-clip-text bg-gradient-to-r from-rose-500 via-purple-400 to-pink-200 animate-gradient-text">
            ReqCool
          </button>
        </div>

        <div className="flex w-full mt-5 justify-center items-center">
          <div className="w-full md:max-w-[600px]">
            <div className="gap-1 flex">
              <input placeholder="https://" className="w-full bg-dark-light rounded-md border-2 border-transparent flex-grow focus:border-purple-400 text-purple-400 px-3 py-2 focus:outline-none" />
              <select
                className="bg-dark-light text-purple-400 px-2 py-2 rounded-md focus:outline-none focus:border-purple-400 border-2 border-transparent"
              >
                <option>GET</option>
                <option>POST</option>
                <option>PUT</option>
                <option>PATCH</option>
                <option>DELETE</option>
                <option>HEAD</option>
                <option>OPTIONS</option>
              </select>
              <button
                className="px-3 focus:outline-none focus:bg-purple-400 py-2 rounded-md border-2 border-purple-400 hover:bg-purple-400 bg-dark-light"
              >
                Send
              </button>
            </div>

            <div className="mt-5">
              <div className="flex gap-1">
                <AnimateSharedLayout>

                  <TabBtn
                    text="Authorization"
                    tab={tab}
                    setTab={setTab}
                    my={0}
                  />
                  <TabBtn
                    text="Content"
                    tab={tab}
                    setTab={setTab}
                    my={1}
                  />
                  <TabBtn
                    text="Headers"
                    tab={tab}
                    setTab={setTab}
                    my={2}
                  />
                </AnimateSharedLayout>
              </div>
              {tab === 0 && <AuthTab />}
              {tab === 1 && <ContentTab />}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

const TabBtn = ({ tab, text, my, setTab }: {
  tab: number;
  my: number;
  text: React.ReactNode;
  setTab: (tab: number) => void;
}) => {

  const spring = {
    type: "spring",
    stiffness: 500,
    damping: 30,
  };

  return (
    <button className={`px-4 relative py-2 rounded-md`} onClick={() => setTab(my)}>
      {tab === my &&
        <motion.div
          layoutId="onTab"
          initial={false}
          transition={spring}
          className="absolute top-0 left-0 w-full h-full bg-purple-100/5 rounded-md"
        />
      }
      <h1 className="text-white">{text}</h1>
    </button>
  )
}

const AuthTab = () => {

  const [auth, setAuth] = useState<"basic" | "bearer" | "custom">("bearer");

  return (
    <div className="mt-2 w-full p-5 rounded-md">
      <form className="flex gap-5 justify-center items-center mb-5">
        <div className="flex gap-2 justify-center items-center">
          <input defaultChecked onClick={() => setAuth("bearer")} name="auth-radio" value="bearer-radio" type="radio" className="accent-purple-400" /><label>Bearer Token</label>
        </div>
        <div className="flex gap-2 justify-center items-center">
          <input onClick={() => setAuth("basic")} name="auth-radio" value="basic-radio" type="radio" className="accent-purple-400" /><label>Basic Auth</label>
        </div>
        <div className="flex gap-2 justify-center items-center">
          <input onClick={() => setAuth("custom")} name="auth-radio" value="custom-radio" type="radio" className="accent-purple-400" /><label>Custom</label>
        </div>
      </form>
      {auth === "bearer" && (
        <div className="flex gap-3 justify-center items-start">
          <h1 className="text-lg mt-2">Token</h1>
          <div className="flex flex-col w-full">
            <input className="w-full bg-dark-light rounded-md border-2 border-transparent flex-grow focus:border-purple-400 text-purple-400 px-3 py-2 focus:outline-none" />
            <p className="text-xs mt-2 text-light-dark/80">The authorization header will be automatically generated when you send the request.</p>
          </div>
        </div>
      )}
      {auth === "basic" && (
        <div className="flex flex-col gap-2 items-center justify-center">
          <h1 className="text-lg font-bold">Basic Authorization</h1>
          <input placeholder="Username" className="w-full bg-dark-light rounded-md border-2 border-transparent flex-grow focus:border-purple-400 text-purple-400 px-3 py-2 focus:outline-none" />
          <input placeholder="Password" className="w-full bg-dark-light rounded-md border-2 border-transparent flex-grow focus:border-purple-400 text-purple-400 px-3 py-2 focus:outline-none" />
          <p className="text-xs mt-1 text-light-dark/80">The authorization header will be automatically generated when you send the request.</p>
        </div>
      )}
      {auth === "custom" && (
        <div className="flex gap-3 justify-center items-start">
          <h1 className="text-lg mt-2">Authorization</h1>
          <div className="flex flex-col w-full">
            <input className="w-full bg-dark-light rounded-md border-2 border-transparent flex-grow focus:border-purple-400 text-purple-400 px-3 py-2 focus:outline-none" />
            <p className="text-xs mt-2 text-light-dark/80">The authorization header will be automatically generated when you send the request.</p>
          </div>
        </div>
      )}

    </div>
  )
}

const ContentTab = () => {

  const [val, setVal] = useState("");
  const [v, setV] = useState("");

  return (
    <div className="mt-2 w-full p-5 rounded-md">
      <select
        onChange={(e) => setV(e.target.value)}
        className="my-3 bg-dark-light w-full text-purple-400 px-2 py-2 rounded-md focus:outline-none focus:border-purple-400 border-2 border-transparent"
      >
        <option>FORM URL Encoded (application/x-www-form-urlencoded)</option>
        <option>JSON (application/json)</option>
        <option>HTML (text/html)</option>
        <option>XML (application/xml)</option>
        <option>TEXT (text/plain)</option>
        <option>CUSTOM (from Headers)</option>
      </select>
      <CodeMirror
        value={val}
        height="200px"
        theme={dracula}
        onChange={setVal}
        extensions={[v.startsWith("FORM") ? html() : (v.startsWith("JSON") ? json(): json())]}
      />
    </div>
  )
}

export default Home;
